[package]
name = "make_structs_from_xsd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"]}
quick-xml = { version = "*", features = ["serialize", "overlapped-lists"] }
