[package]
name = "make_structs_from_xsd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"]}
quick-xml = { version = "0.37.2", features = ["serialize", "overlapped-lists"] }
tera = "1.20.0"
convert_case = "0.6.0"
